### PR TITLE
Minor Fixes; Incomplete PR

### PR DESCRIPTION
**Pull request by jesbu1**
The plotting functions have been added to the `timeline_unimodal_car_bike_lost_altos.ipynb`. I'm not sure where best to put these in the codebase so that we can reuse them across notebooks, but they're in this timeline for now so that you can take a look.

Also made a minor typo fix and linked to where a function is in the repository in the data exploration ipynb.

### CODE REVIEW

**Comment by shankari** [comment]
@jesbu1 can you please resolve the merge conflict? You should also end up pulling from master to do so, which is good, because it will run the automated tests with the PR and give me confidence to merge.

**Comment by shankari** [comment]
@jesbu1 there are still merge conflicts in `timeline_unimodal_car_bike_los_altos.ipynb`

**Comment by jesbu1** [comment]
Sorry didn't see the above comment earlier. Merge conflict addressed.

**Comment by shankari** [comment]
Can you either remove `Evaluations_power_boxplots.ipynb`, or check it in after clearing outputs (Kernel -> Restart and clear outputs)? Checking in notebooks with outputs included makes it almost impossible to see the changes in subsequent revisions.

**Comment by jesbu1** [comment]
Yes, I have just pushed that change

**Pull request merged**
